spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdemomovie
    username: postgres
    password: password
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
